### ISSUE TITLE
安装完成后卡进度条, 风扇一直转

### ISSUE THREAD

**Issue by liloew** [SunSeekerX/hasee-g8-ca5ns-NH5x_7xDPx-hackintosh-opencore#3]
如题，安装完成后卡进度条无任何反应，风扇一直狂转无任何反应。
是哪里设置的不对吗？
镜像用的是 macOS Ventura 13.2 22D49 Installer for OpenCore 0.8.8 and FirPE

**Comment by liloew** [comment]
型号 Zg-CA5NP, 和Z8-CA5NB是同型号，只是屏幕有所不同。

**Comment by SunSeekerX** [comment]
> 如题，安装完成后卡进度条无任何反应，风扇一直狂转无任何反应。 是哪里设置的不对吗？ 镜像用的是 macOS Ventura 13.2 22D49 Installer for OpenCore 0.8.8 and FirPE

重启下，多重启几次，我偶尔也遇到
